apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  ports:
  - name: ftps21
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftps30000
    port: 30000
    protocol: TCP
    targetPort: 30000
  - name: ftps30020
    port: 30020
    protocol: TCP
    targetPort: 30020
  - name: ftps30021
    port: 30021
    protocol: TCP
    targetPort: 30021
  selector:
    app: ftps
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30000
        - containerPort: 30001
        - containerPort: 30002
