apiVersion: v1
kind: Service
metadata:
  name: telegraf
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: telegraf
spec:
  selector:
    app: telegraf
  ports:
  - protocol: UDP
    port: 8125
    targetPort: 8125
  type: ClusterIP

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  labels:
    app: telegraf
data:
  telegraf.conf: |
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      gather_services = false
      container_names = []
      source_tag = false
      container_name_include = []
      container_name_exclude = []
      timeout = "20s"
      perdevice = true
      total = false
      docker_label_include = []
      docker_label_exclude = []
      tag_env = ["JAVA_HOME", "HEAP_SIZE"]
    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      skip_database_creation = false
      database = "telegrafana"
      username = "admin"
      password = "password"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: telegraf-img
        name: telegraf
        imagePullPolicy: Never
        volumeMounts:
        - name: telegraf-config-volume
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock